name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r Streamlit/requirements.txt

      - name: Train model
        run: |
          source venv/bin/activate
          python Streamlit/train.py

      - name: Check File Location After Training
        run: |
          echo "Checking file location and contents"
          ls -la Streamlit
          find . -name "results.txt"
          cat Streamlit/results.txt  # Print out the contents of results.txt


      - name: Create report.md
        run: |
          cat Streamlit/results.txt > report.md
          echo "![](Streamlit/feature_importance.png)" >> report.md
          echo "![](Streamlit/residuals.png)" >> report.md

      - name: Commit results and report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Streamlit/results.txt Streamlit/report.md Streamlit/feature_importance.png Streamlit/residuals.png
          git commit -m "Add model results and report"
          git push

      - name: Create CML Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          cml comment create report.md --token ${{ secrets.GITHUB_TOKEN }}



# name: model-training
# on: [push]
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#       - uses: iterative/setup-cml@v1
#       - name: Set up Python environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install --upgrade pip
#           pip install -r Streamlit/requirements.txt

#       - name: Train model
#         env:
#           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           source venv/bin/activate
#           python Streamlit/train.py

#           cat Streamlit/results.txt >> report.md
#           echo "![](./plot.png)" >> report.md
#           cml comment create Streamlit/report.md
