name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    #sub docker line below for users, maybe will allow for mds to show up?
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: iterative/setup-cml@v1
    - name: Train model
      run: |
        # Your ML workflow goes here
        pip install -r Streamlit/requirements.txt
        python Streamlit/train.py

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Post reports as comments in GitHub PRs
        cat Streamlit/results.txt >> report.md
        cml comment create report.md
