[theme]
primaryColor = "#076652"
backgroundColor = "#FFFFFF"  # Adjust if you want a different background
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"  # You can change this to other fonts if desired
